-- Catálogo fijo de artículos deportivos (no requiere mantenimiento desde la aplicación).
INSERT INTO categories (slug, name) VALUES
    ('futbol', 'Fútbol'),
    ('running', 'Running'),
    ('basquetbol', 'Básquetbol'),
    ('tenis', 'Tenis'),
    ('fitness', 'Fitness'),
    ('ciclismo', 'Ciclismo'),
    ('natacion', 'Natación');

INSERT INTO products (sku, name, description, brand, category_id, price, stock, image_url) VALUES
    ('FUT-001', 'Balón de Fútbol Pro Match',
     'Balón oficial talla 5 con paneles termosellados, cámara de butilo y superficie texturizada para un mejor control y precisión en cada pase.',
     'Striker', (SELECT id FROM categories WHERE slug = 'futbol'), 39.99, 25, '/api/products/images/balon-futbol.svg'),
    ('FUT-002', 'Zapatos de Fútbol Velocity FG',
     'Tacos para césped natural con upper sintético ultraligero, suela de TPU y tacos cónicos que facilitan los cambios de dirección.',
     'Velocity', (SELECT id FROM categories WHERE slug = 'futbol'), 89.90, 12, '/api/products/images/zapatos-futbol.svg'),
    ('FUT-003', 'Guantes de Portero Grip Pro',
     'Palma de látex de 4 mm con agarre en seco y mojado, cierre de muñeca ajustable y protección para los dedos.',
     'Striker', (SELECT id FROM categories WHERE slug = 'futbol'), 34.50, 18, '/api/products/images/guantes-portero.svg'),
    ('RUN-001', 'Zapatillas Running CloudRun',
     'Amortiguación de espuma reactiva, malla transpirable y suela de caucho de alta tracción, ideales para entrenamientos de larga distancia.',
     'CloudRun', (SELECT id FROM categories WHERE slug = 'running'), 119.00, 20, '/api/products/images/zapatillas-running.svg'),
    ('RUN-002', 'Reloj Deportivo GPS Pulse',
     'GPS integrado, monitor de frecuencia cardíaca en la muñeca, resistencia al agua 5 ATM y hasta 10 días de batería.',
     'Pulse', (SELECT id FROM categories WHERE slug = 'running'), 149.99, 7, '/api/products/images/reloj-gps.svg'),
    ('RUN-003', 'Botella de Hidratación 750 ml',
     'Acero inoxidable de doble pared que mantiene tu bebida fría por 24 horas. Libre de BPA y a prueba de fugas.',
     'HydroGo', (SELECT id FROM categories WHERE slug = 'running'), 19.99, 40, '/api/products/images/botella.svg'),
    ('BAS-001', 'Balón de Básquetbol Street',
     'Balón talla 7 de caucho compuesto de alta durabilidad, con canales profundos para un agarre seguro en canchas exteriores e interiores.',
     'Hoops', (SELECT id FROM categories WHERE slug = 'basquetbol'), 29.99, 22, '/api/products/images/balon-basquet.svg'),
    ('BAS-002', 'Zapatillas de Básquetbol SkyJump',
     'Caña alta con soporte de tobillo, cámara de aire en el talón y suela de goma con patrón de espiga para máxima tracción.',
     'Hoops', (SELECT id FROM categories WHERE slug = 'basquetbol'), 99.00, 14, '/api/products/images/zapatillas-basquet.svg'),
    ('TEN-001', 'Raqueta de Tenis Carbon Ace',
     'Marco de fibra de carbono de 300 g, cabeza de 100 in² y patrón de cuerdas 16x19 que combina potencia y control.',
     'Ace', (SELECT id FROM categories WHERE slug = 'tenis'), 129.00, 9, '/api/products/images/raqueta-tenis.svg'),
    ('TEN-002', 'Tubo de Pelotas de Tenis (3 u.)',
     'Pelotas presurizadas aprobadas para torneo, con fieltro de alta visibilidad apto para todo tipo de superficie.',
     'Ace', (SELECT id FROM categories WHERE slug = 'tenis'), 7.99, 60, '/api/products/images/pelotas-tenis.svg'),
    ('FIT-001', 'Set de Mancuernas Ajustables 2 x 5 kg',
     'Par de mancuernas con discos intercambiables y agarre antideslizante. Incluye seguros de rosca y estuche.',
     'IronCore', (SELECT id FROM categories WHERE slug = 'fitness'), 54.90, 15, '/api/products/images/mancuernas.svg'),
    ('FIT-002', 'Mat de Yoga Antideslizante 6 mm',
     'Material TPE ecológico de doble cara antideslizante, con líneas de alineación y correa para transportarlo.',
     'Zen', (SELECT id FROM categories WHERE slug = 'fitness'), 24.99, 30, '/api/products/images/mat-yoga.svg'),
    ('FIT-003', 'Cuerda para Saltar Speed Pro',
     'Cable de acero recubierto, rodamientos de alta velocidad y longitud ajustable, perfecta para entrenamiento de alta intensidad.',
     'IronCore', (SELECT id FROM categories WHERE slug = 'fitness'), 12.50, 3, '/api/products/images/cuerda-saltar.svg'),
    ('FIT-004', 'Kettlebell de Hierro 12 kg',
     'Hierro fundido con recubrimiento de vinilo que protege el piso y asa amplia para ejercicios funcionales a una o dos manos.',
     'IronCore', (SELECT id FROM categories WHERE slug = 'fitness'), 45.00, 0, '/api/products/images/kettlebell.svg'),
    ('FIT-005', 'Camiseta de Entrenamiento DryFit',
     'Tela de secado rápido con tratamiento anti olor y costuras planas que evitan rozaduras durante el ejercicio.',
     'Velocity', (SELECT id FROM categories WHERE slug = 'fitness'), 22.00, 35, '/api/products/images/camiseta.svg'),
    ('CIC-001', 'Casco de Ciclismo Aero',
     'Carcasa in-mold con 18 ventilaciones, sistema de ajuste 360° y visera desmontable. Certificado para ruta y montaña.',
     'RideSafe', (SELECT id FROM categories WHERE slug = 'ciclismo'), 69.99, 10, '/api/products/images/casco-ciclismo.svg'),
    ('NAT-001', 'Gafas de Natación Pro Vision',
     'Lentes antiempañante con protección UV, sello de silicona hipoalergénico y correa dividida de ajuste rápido.',
     'AquaPro', (SELECT id FROM categories WHERE slug = 'natacion'), 18.75, 28, '/api/products/images/gafas-natacion.svg'),
    ('NAT-002', 'Gorro de Natación de Silicona',
     'Silicona premium resistente al cloro, interior texturizado que evita que se deslice y ajuste cómodo para cabello largo.',
     'AquaPro', (SELECT id FROM categories WHERE slug = 'natacion'), 11.90, 45, '/api/products/images/gorro-natacion.svg');
